//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int Id { get; set; }
        public decimal FullPrice { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual Sales Sales { get; set; }
    }
}
